service: aws-node-rest-api-typescript

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    NODE_ENV: dev
    DYNAMO_DB_TABLE: blog_project_table
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMO_DB_TABLE}"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  hello:
    handler: src/handler.getAllBlogs
    events:
      - http:
          path: /allblogs
          method: get
          cors: true
